drop table if exists public.deposited_money cascade;
drop table if exists public.people cascade;
create table public.deposited_money (id int4 generated by default as identity, money float8 not null, who int4, whom int4, primary key (id));
create table public.people (id int4 generated by default as identity, birthday timestamp not null, name varchar(255) not null, primary key (id));
alter table if exists public.deposited_money add constraint FKt4knlobidx0f44nl0cmhp863g foreign key (who) references public.people;
alter table if exists public.deposited_money add constraint FK2c8q4bpu7mqft5asruo5uu7dq foreign key (whom) references public.people;
